
command('app build'): |
  #!bash(workspace:/)|@
  ws app build console
  ws app build php-fpm
  ws app build job-queue-consumer
  ws app build cron
  ws app build nginx

command('app build job-queue-consumer'): |
  #!bash(workspace:/)|@
  passthru docker build -t @('docker.repository'):@('app.version')-job-queue-consumer -f .my127ws/docker/image/job-queue-consumer/Dockerfile .

command('app publish'): |
  #!bash(workspace:/)|@
  echo "@('docker.password')" | run docker login --username="@('docker.username')" --password-stdin @('docker.registry_url')
  run docker push @('docker.repository'):@('app.version')-console
  run docker push @('docker.repository'):@('app.version')-php-fpm
  run docker push @('docker.repository'):@('app.version')-job-queue-consumer
  run docker push @('docker.repository'):@('app.version')-cron
  run docker push @('docker.repository'):@('app.version')-nginx
  run docker logout @('docker.registry_url')

