{{ if and .Values.persistence.rabbitmq.enabled (.Values.service.rabbitmq | default .Values.docker.services.rabbitmq.enabled) -}}

{{- with .Values.persistence.rabbitmq -}}

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ $.Values.resourcePrefix }}rabbitmq-pv-claim
  labels:
    {{- include "chart.labels" $ | nindent 4 }}
    app.kubernetes.io/component: rabbitmq
    app.service: {{ $.Values.resourcePrefix }}rabbitmq
spec:
  accessModes:
    - {{ .accessMode | quote }}
  resources:
    requests:
      storage: {{ .size | quote }}
{{- if .storageClass }}
{{- if (eq "-" .storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: {{ .storageClass | quote }}
{{- end }}
{{- end }}
{{- if .selector }}
  selector:
  {{- .selector | toYaml | nindent 4 }}
{{- end }}

{{- end }}

{{- end }}
