{{- if .Values.persistence.enabled -}}
{{- with .Values.persistence.magento.media -}}
{{- if .hostPath }}
---
kind: PersistentVolume
metadata:
  name: magento-media
spec:
  capacity: {{ .size | quote }}
  accessModes:
    - {{ .accessMode | quote }}
  hostPath:
    path: {{ .hostPath | quote }}
  storageClassName: host-magento-media
...
{{- end }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: magento-media-pvc
spec:
  accessModes:
    - {{ .accessMode | quote }}
  resources:
    requests:
      storage: {{ .size | quote }}
{{- if .hostPath }}
      storageClassName: host-magento-media
{{- else }}
{{- if .storageClass }}
{{- if (eq "-" .storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: {{ .storageClass | quote }}
{{- end }}
{{- end }}
{{- end }}
{{- if .selector }}
  selector:
  {{- .selector | toYaml | nindent 4 }}
{{- end }}
...
{{- end -}}
{{- end -}}
