# this file is not considered part of the public API so changes aren't considered breaking
confd('harness:/'):
  # base templates
  - { src: docker/image/console/Dockerfile }
  - { src: docker/image/console/root/home/build/.my.cnf }
  - { src: docker/image/console/root/lib/task/database/import.sh }
  - { src: docker/image/console/root/lib/task/build/frontend.sh }
  - { src: docker/image/console/root/lib/task/build/backend.sh }
  - { src: docker/image/console/root/lib/task/init.sh }
  - { src: docker/image/console/root/lib/task/install.sh }
  - { src: docker/image/console/root/lib/task/migrate.sh }
  - { src: docker/image/console/root/lib/task/rabbitmq/vhosts.sh }
  - { src: docker/image/console/root/lib/task/welcome.sh }
  - { src: docker/image/console/root/usr/local/etc/php/php.ini }
  - { src: docker/image/console/root/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini }
  - { src: docker/image/nginx/Dockerfile }
  - { src: docker/image/nginx/root/docker-entrypoint.d/config_render.sh }
  - { src: docker/image/nginx/root/etc/nginx/conf.d/0-nginx.conf }
  #- { src: docker/image/nginx/root/etc/nginx/conf.d/default.conf.template } Deliberately missing
  - { src: docker/image/nginx/root/etc/ssl/certs/app.crt }
  - { src: docker/image/nginx/root/etc/ssl/private/app.key }
  - { src: docker/image/php-fpm/Dockerfile }
  - { src: docker/image/php-fpm/root/entrypoint.sh }
  - { src: docker/image/php-fpm/root/fix_app_permissions.sh }
  - { src: docker/image/php-fpm/root/usr/local/etc/php/php.ini }
  - { src: docker/image/php-fpm/root/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini }
  - { src: docker/image/php-fpm/root/usr/local/etc/php-fpm.d/pool.conf.template }
  - { src: docker/image/tls-offload/root/etc/nginx/conf.d/0-nginx.conf }
  - { src: docker/image/tls-offload/root/etc/nginx/conf.d/default.conf }
  - { src: docker/image/tls-offload/root/etc/ssl/certs/app.crt }
  - { src: docker/image/tls-offload/root/etc/ssl/private/app.key }
  - { src: docker/image/varnish/root/etc/varnish/default.vcl }
  - { src: docker/image/cron/Dockerfile }
  - { src: docker/image/cron/root/crontab }
  - { src: application/overlay/Jenkinsfile }
  - { src: application/overlay/auth.json }
  - { src: application/overlay/.dockerignore, dst: workspace:/.dockerignore }
  - { src: application/skeleton/README.md }
  - { src: docker-compose.yml, dst: workspace:/docker-compose.yml }
  - { src: docker-sync.yml, dst: workspace:/docker-sync.yml }
  - { src: mutagen.yml, dst: workspace:/mutagen.yml }
  - { src: harness/scripts/enable.sh }
  - { src: helm/app/_twig/templates/service/varnish/configmap.yaml, dst: harness:/helm/app/templates/service/varnish/configmap.yaml }
  - { src: helm/app/values.yaml }
  - { src: helm/app/values-production.yaml }
  - { src: helm/app/values-preview.yaml }
  - { src: helm/app/Chart.yaml }
  - { src: helm/qa/requirements.yaml }
  - { src: helm/qa/values.yaml }
  - { src: helm/qa/Chart.yaml }
  # harness-spryker templates
  - { src: application/skeleton/config/install/docker.yml }
  - { src: docker/image/console/root/lib/task/skeleton/apply.sh }
  - { src: docker/image/console/root/lib/task/spryker/build.sh }
  - { src: docker/image/nginx/root/etc/nginx/conf.d/glue.conf.template }
  - { src: docker/image/nginx/root/etc/nginx/conf.d/yves.conf.template }
  - { src: docker/image/nginx/root/etc/nginx/conf.d/zed.conf.template }
  - { src: docker/image/jenkins-runner/Dockerfile }
  - { src: helm/preview/requirements.yaml }
  - { src: helm/preview/values.yaml }
