
confd('harness:/'):
  # base templates
  - { src: docker/image/console/Dockerfile }
  - { src: docker/image/console/root/home/build/.my.cnf }
  - { src: docker/image/console/root/lib/task/assets/apply.sh }
  - { src: docker/image/console/root/lib/task/assets/dump.sh }
  - { src: docker/image/console/root/lib/task/build/frontend.sh }
  - { src: docker/image/console/root/lib/task/build/backend.sh }
  - { src: docker/image/console/root/lib/task/database/available.sh }
  - { src: docker/image/console/root/lib/task/init.sh }
  - { src: docker/image/console/root/lib/task/install.sh }
  - { src: docker/image/console/root/lib/task/migrate.sh }
  - { src: docker/image/console/root/usr/local/etc/php/php.ini }
  - { src: docker/image/console/root/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini }
  - { src: docker/image/nginx/Dockerfile }
  - { src: docker/image/nginx/root/etc/nginx/conf.d/0-nginx.conf }
  - { src: docker/image/nginx/root/etc/ssl/certs/app.crt }
  - { src: docker/image/nginx/root/etc/ssl/private/app.key }
  - { src: docker/image/php-fpm/Dockerfile }
  - { src: docker/image/php-fpm/root/fix_app_permissions.sh }
  - { src: docker/image/php-fpm/root/usr/local/etc/php/php.ini }
  - { src: docker/image/php-fpm/root/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini }
  - { src: application/overlay/Jenkinsfile }
  - { src: application/overlay/auth.json }
  - { src: application/overlay/.dockerignore, dst: workspace:/.dockerignore }
  - { src: application/skeleton/README.md }
  - { src: docker-compose.yml, dst: workspace:/docker-compose.yml }
  - { src: docker-sync.yml, dst: workspace:/docker-sync.yml }
  - { src: helm/app/values.yaml }
  - { src: helm/qa/values.yaml }
  # harness-spryker templates
  - { src: application/skeleton/.gitignore }
  - { src: application/skeleton/config/install/docker.yml }
  - { src: docker/image/console/root/lib/task/rabbitmq/vhosts.sh }
  - { src: docker/image/console/root/lib/task/skeleton/apply.sh }
  - { src: docker/image/console/root/lib/task/welcome.sh }
  - { src: docker/image/nginx/root/docker-entrypoint.d/config_render.sh }
  - { src: docker/image/nginx/root/etc/nginx/conf.d/glue.conf.template }
  - { src: docker/image/nginx/root/etc/nginx/conf.d/yves.conf.template }
  - { src: docker/image/nginx/root/etc/nginx/conf.d/zed.conf.template }
  - { src: docker/image/jenkins-runner/Dockerfile }
  - { src: helm/preview/values.yaml }
