
confd('harness:/'):
  # base templates
  - { src: docker/image/console/Dockerfile }
  - { src: docker/image/console/root/home/build/.my.cnf }
  - { src: docker/image/console/root/lib/task/assets/apply.sh }
  - { src: docker/image/console/root/lib/task/assets/dump.sh }
  - { src: docker/image/console/root/lib/task/build/frontend.sh }
  - { src: docker/image/console/root/lib/task/build/backend.sh }
  - { src: docker/image/console/root/lib/task/database/available.sh }
  - { src: docker/image/console/root/lib/task/init.sh }
  - { src: docker/image/console/root/lib/task/install.sh }
  - { src: docker/image/console/root/usr/local/etc/php/php.ini }
  - { src: docker/image/console/root/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini }
  - { src: docker/image/nginx/Dockerfile }
  - { src: docker/image/nginx/root/etc/nginx/conf.d/default.conf }
  - { src: docker/image/nginx/root/etc/ssl/certs/app.crt }
  - { src: docker/image/nginx/root/etc/ssl/private/app.key }
  - { src: docker/image/php-fpm/Dockerfile }
  - { src: docker/image/php-fpm/root/fix_app_permissions.sh }
  - { src: docker/image/php-fpm/root/usr/local/etc/php/php.ini }
  - { src: docker/image/php-fpm/root/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini }
  - { src: application/overlay/auth.json }
  - { src: application/overlay/Jenkinsfile }
  - { src: application/overlay/.dockerignore, dst: workspace:/.dockerignore }
  - { src: application/skeleton/README.md }
  - { src: docker-compose.yml, dst: workspace:/docker-compose.yml }
  - { src: docker-sync.yml, dst: workspace:/docker-sync.yml }
  - { src: helm/app/values.yaml }
  - { src: helm/qa/values.yaml }
  # harness-drupal templates
  - { src: application/overlay/docroot/sites/default/settings.local.php }
  - { src: application/overlay/phpcs.xml }
  - { src: application/overlay/phpunit.xml }
  - { src: application/skeleton/behat.yml }
  - { src: application/skeleton/.gitignore }
