{{- $root := . -}}
{{ if eq .Values.ingress "standard" }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    app.service: {{ .Values.prefix }}nginx
  name: {{ .Values.prefix }}nginx
spec:
  rules:
  {{- range $key, $value := .Values.docker.services.nginx.environment }}
  - host: {{ $value | quote }}
    http:
      paths:
      - backend:
          serviceName: {{ $root.Values.prefix }}nginx
          servicePort: 80
  {{- end }}
status:
  loadBalancer: {}
{{ end }}
